{{- if and (eq (include "token-validator.teamsEnabled" .) "true") .Values.teamsWebhook.webhookUrl (not .Values.teamsWebhook.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "token-validator.teamsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "token-validator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.teamsWebhook.existingSecretKey }}: {{ .Values.teamsWebhook.webhookUrl | quote }}
{{- end -}}
